project:
  type: website

website:
  title: "RDKit blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rdkit/rdkit
      - icon: twitter
        href: https://twitter.com/rdkit_org
format:
  html:
    theme: cosmo
    css: styles.css



