project:
  type: website
  output-dir: docs

website:
  title: "RDKit blog"
  favicon: posts/icons/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rdkit/rdkit
      - icon: twitter
        href: https://twitter.com/rdkit_org
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

comments:
  utterances:
    repo: greglandrum/rdkit-blog

