project:
  type: website
  output-dir: docs

website:
  title: "RDKit blog"
  site-url: https://greglandrum.github.io/rdkit-blog/
  description: "RDKit experiments, tips, and tutorials"
  favicon: posts/icons/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rdkit/rdkit
      - icon: twitter
        href: https://twitter.com/rdkit_org
      - icon: rss
        href: index.xml
  page-footer:
    left: |
      Copyright (C) 2024 Greg Landrum
    right: |
      [![](https://www.rdkit.org/logo.small.png){fig-alt="RDKit" width=64px}](https://www.rdkit.org)

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header:
      text: |
        <script defer async data-host="greglandrum.github.io" src="https://liteanalytics.com/lite.js"></script>

comments:
  utterances:
    repo: greglandrum/rdkit-blog

execute:
  freeze: auto

